pengsoft:
  oss:
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    public-bucket: ${OSS_PUBLIC_BUCKET_NAME}
    locked-bucket: ${OSS_LOCKED_BUCKET_NAME}
    endpoint: ${OSS_ENDPOINT}
    public-access-path-prefix: ${OSS_PUBLIC_BUCKET_ACCESS_PATH_PREFIX}
    locked-access-path-prefix: ${OSS_LOCKED_BUCKET_ACCESS_PATH_PREFIX}
