package com.pengsoft.system.biz.repository;

import com.pengsoft.security.domain.entity.User;
import com.pengsoft.support.biz.repository.EntityRepository;
import com.pengsoft.system.domain.entity.Captcha;
import com.pengsoft.system.domain.entity.QCaptcha;
import com.querydsl.core.types.dsl.DateTimePath;
import org.springframework.data.jpa.repository.QueryHints;
import org.springframework.data.querydsl.binding.QuerydslBindings;
import org.springframework.stereotype.Repository;

import javax.persistence.QueryHint;
import java.time.LocalDateTime;
import java.util.List;

/**
 * The repository interface of {@link Captcha} based on JPA
 *
 * @author dang.peng@pengsoft.com
 * @since 1.0.0
 */
@Repository
public interface CaptchaRepository extends EntityRepository<QCaptcha, Captcha, String> {

    @Override
    default void customize(final QuerydslBindings bindings, final QCaptcha root) {
        EntityRepository.super.customize(bindings, root);
        bindings.bind(root.expiredAt).first(DateTimePath::before);
    }

    /**
     * Returns all entities generated by user, with type and after createdAt
     * @param userId {@link User} The user id
     * @param createdAt {@link LocalDateTime} The captcha created at.
     */
    @QueryHints(value = @QueryHint(name = "org.hibernate.cacheable", value = "true"), forCounting = false)
    List<Captcha> findAllByUserIdAndCreatedAtAfterOrderByCreatedAtDesc(String userId, LocalDateTime createdAt);

}
