spring:
  messages:
    basename: META-INF/validations, META-INF/validations-security
logging:
  level:
    org.springframework.security: debug
pengsoft:
  security:
    oauth:
      authorization-server: enabled
      resource-server: enabled